#General settings of the experiment
experiment: 
  name: "Training"
  weights_filename: "../weights/mlp_weights.pth"
  weights_classifier: "../weights/autoencoder_weights.pth"
training: 
  num_samples: 10000
  train_split: 0.2
  n_epochs: 200
  lr: 0.003
model: 
  hidden_dim: 512